set_global_assignment -name VERILOG_MACRO "CORENAME=\"JTCONTRA\""
set_global_assignment -name VERILOG_MACRO "VERTICAL_SCREEN=1"
set_global_assignment -name VERILOG_MACRO "JTFRAME_CLK24=1"
set_global_assignment -name VERILOG_MACRO "JTFRAME_MRA_DIP=1"
set_global_assignment -name VERILOG_MACRO "GAMETOP=jtcontra_game"
set_global_assignment -name VERILOG_MACRO "STEREO_GAME=1"
set_global_assignment -name VERILOG_MACRO "JT51=1"
set_global_assignment -name VERILOG_MACRO "COLORW=5"
set_global_assignment -name VERILOG_MACRO "VIDEO_WIDTH=280"
set_global_assignment -name VERILOG_MACRO "VIDEO_HEIGHT=240"
set_global_assignment -name VERILOG_MACRO "BUTTONS=2"
set_global_assignment -name VERILOG_MACRO "JTFRAME_ARX=4"
set_global_assignment -name VERILOG_MACRO "JTFRAME_ARY=3"

